### PR TITLE
fix: placeholder image height on the collections page

### LINKED ISSUE #181: [Bug]: Error while getting products without assets
### Expected Behavior

If any product does not have assets, it should still be displayed without an image or with a placeholder image.

### Actual Behavior

Now throwing a runtime error and the entire category page is not displayed.

TypeError: Cannot read properties of null (reading 'sort')
    at Object.getAgnosticSearchResult (facetGetters.ts?f8dc:129:1)
    at VueComponent.eval (VM17945 Category.vue:439:84)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495:1)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4597:1)
    at RefImpl.computedGetter [as value] (vue-composition-api.esm.js?a6f4:1093:1)
    at VueComponent.eval (VM17945 Category.vue:451:120)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495:1)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4597:1)
    at RefImpl.computedGetter [as value] (vue-composition-api.esm.js?a6f4:1093:1)
    at VueComponent.eval (VM17945 Category.vue:454:56)

### Possible Solution

_No response_

### Steps to reproduce

1. Add a product without an image in Vendure. 
2. Start Storefront
3. Navigate to the category page which contains that product

### What version of vendure integration are you using?

1.1.0

### What version of Node.js are you using?

16.10.0

### What browser (and version) are you using?

Chrome Version 98.0.4758.109

### What operating system (and version) are you using?

macOS v12.2.1

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ymaheshwari1**
## Description

Added height for the placeholder component

## Related Issue

closes #181 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey @ymaheshwari1 

Sorry for keep you waiting. I was bit busy with other tasks. 

I dont think that this will solve the issue becuase the bug was reported as an issue in the javascript, not the styles.

**Comment by ymaheshwari1** [comment]
> Hey @ymaheshwari1
> 
> Sorry for keep you waiting. I was bit busy with other tasks.
> 
> I dont think that this will solve the issue becuase the bug was reported as an issue in the javascript, not the styles.

Hi @Baroshem 
Actually the placeholder image gets loaded always but the issue is that the height of the image is so small that's it is not properly visible.

**Comment by Baroshem** [comment]
@ymaheshwari1 

But the problem is that we expect that the product will contain image, while in some cases you may not have an image. So in here, an optional chaining should be added in order to avoid bugs such as the one reported by the issue reporter

**Comment by Baroshem** [comment]
Decided to close this PR as it does not solve the issue. I will work on it and develop a different fix instead.

**Pull request closed without merging**
