### PR TITLE
(fix) Customer name not displayed in account form on first load

### PR DESCRIPTION
**Pull request by justyna-13**
## Related Issue
#125 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Baroshem** [comment]
Thanks for that PR @justyna-13 !

Could you also please check if the following issue does appear in other tabs of profile page? Like change user email, forgot password, etc? I think if the user is not loaded properly on the first tab it would also not be loaded on other tabs, but I may be wrong :)

**Comment by Baroshem** [comment]
Apart from that, this PR is ready for merge :)

**Comment by justyna-13** [comment]
> Thanks for that PR @justyna-13 !
> 
> Could you also please check if the following issue does appear in other tabs of profile page? Like change user email, forgot password, etc? I think if the user is not loaded properly on the first tab it would also not be loaded on other tabs, but I may be wrong :)

Sure :) I'll check the rest places

**Comment by justyna-13** [comment]
@Baroshem it seems that the rest places are correct in my account :)

**Comment by justyna-13** [comment]
> Apart from that, this PR is ready for merge :)

still needed one appr :smile:

**Review by Baroshem — APPROVED** [review]
❤️

**Pull request merged**
