### PR TITLE
fix(static pages): handling multiple white spaces inside static page

### PR DESCRIPTION
**Pull request by zmilan**
Fixed issue with handling only the first occurrence of white space in static page title

bug #154

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Baroshem** [comment]
Hi @zmilan 

Thanks for raising this PR. I will merge it in the upcoming days so that we can release it with our new version 1.0.1 :)

**Comment by Baroshem** [comment]
Hi @zmilan 

Could you please also update the changelog of 1.0.1 in the docs? Apart from that, this PR is ready to be merged :)

**Comment by zmilan** [comment]
> Hi @zmilan
> 
> Could you please also update the changelog of 1.0.1 in the docs? Apart from that, this PR is ready to be merged :)

Done :)

**Comment by Baroshem** [comment]
Awesome, merging. 

Well done once again! 

If you are interested, there are also other bugs and features waiting in the backlog. Just let me know in the certain issue that you are interested so I could assign you :)

**Review by Baroshem — APPROVED** [review]
🚀

**Comment by michaelbromley** [comment]
Great work @zmilan! Thanks for your contributions to this project 🙏 👏

**Comment by zmilan** [comment]
Hi, @michaelbromley thanks, expect more from me in the next days/months, since I am working on a solid big shop which uses venture and vsf2... but I work on it only part time and still have some challenges with organizing import/update of big amount of products... but once when that is done I would move more to help about vendure and vsf2...

**Comment by Baroshem** [comment]
@zmilan 

That sounds great! If you will need help at some point, make sure to ping me in Discord or here directly so that we can help you build your shop. If I am not mistaken, this will be a first live VSF & Vendure shop so remember to give us a note so that we can promote your project as well :)

**Comment by zmilan** [comment]
@Baroshem Thanks in advance. I am very happy to be part of this community and both tools are awesome... I will give you an update for sure...

**Pull request merged**
